server:
  port: 8090
spring:
  data:
    mongodb:
      username: yassine
      password: yassineMj
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin